#!/usr/bin/env python

import os
import time
import json
import argparse
from lxml import etree

from scenarios.input_output import parse_bssc2014_ucerf
from scenarios.input_output import parse_json
from scenarios.input_output import parse_json_sub
from scenarios.input_output import write_rupture_files
from scenarios.input_output import write_event_xml


def main(args):
    if args.shakehome:
        shakehome = args.shakehome
    else:
        shakehome = os.path.join(os.path.expanduser('~'), 'ShakeMap')

    # Open rupture file
    rfile = args.file
    with open(rfile) as f:
        rupts = json.load(f)
        nrup = len(rupts['events'])
        print('Total number of ruptures: %d' % nrup)

    if rupts['name'] == '2014 NSHMP Determinisitc Event Set':
        rlist = parse_bssc2014_ucerf(rupts, args)
    elif (rupts['name'] == '2014 NSHMP Determinisitc Event Set WUS outside CA') or\
         (rupts['name'] == '2014 NSHMP Determinisitc Event Set CEUS'):
        rlist = parse_json(rupts, args)
    elif rupts['name'] == '2014 NSHMP Determinisitc Event Set Cascadia':
        rlist = parse_json_sub(rupts, args)
    elif rupts['name'] == '2016 Montanta Scenarios':
        rlist = parse_json(rupts, args)
    else:
        raise Exception('Unknown rupture file type.')


    nrup = len(rlist)

    for i in range(nrup):

        rdict = rlist[i]
        id_str = rdict['id_str']

        #-----------------------------------------------------------------------
        # Write files
        #-----------------------------------------------------------------------

        # Create base directory if it doesn't exist
        datdir = os.path.join(shakehome, 'data')
        if os.path.isdir(datdir) == False:
            os.mkdir(datdir)

        # Create event directory if it doesn't exist
        evt_dir = os.path.join(datdir, id_str)
        if os.path.isdir(evt_dir) == False:
            os.mkdir(evt_dir)
        print(evt_dir)

        # Create input directory if it doesn't exist
        input_dir = os.path.join(evt_dir, 'input')
        if os.path.isdir(input_dir) == False:
            os.mkdir(input_dir)

        #-----------------------------------------------------------------------
        # Write rupture files and event.xml
        #-----------------------------------------------------------------------
        if rdict['rupture'] is not None:
            write_rupture_files(input_dir, rdict)
        
        write_event_xml(input_dir, rdict, args.directivity)



if __name__ == '__main__':
    desc = '''
    Create ShakeMap input directory. This is designed primarily to be used with
    an input file that provides rupture information. Currently, this only 
    supports the BSSC2014 JSON format. 
    
    TODO: 
      * Add support for NSHM XML format
      * Add support for Excel rupture template
      * prompt for minimal info if file is not provided
    '''
    parser = argparse.ArgumentParser(description=desc)
    fh = 'File with rupture information; currently only BSSC2014 JSON format; '\
         'Future: USGS NSHM xml format and Excel rupture template.'
    parser.add_argument('-f', '--file', help=fh)
    parser.add_argument('-r', '--reference', help='Reference for rupture source.',
                        default='')
    parser.add_argument('-d', '--dirind',
                        help='Directivity; -1 for no directivity (default); 0 '\
                        'and 2 are the two opposing unilateral directions, 1 '\
                        'is for bilateral.',
                        default=-1, type=int, choices=[-1, 0, 1, 2])
    parser.add_argument('-i', '--index',
                        help='List of rupture indices to run. Useful if you do '\
                        'not want to run all ruptures in the file.',
                        nargs='*')
    shakehome = os.path.join(os.path.expanduser('~'), 'ShakeMap')
    parser.add_argument(
        '-s', '--shakehome',
        help='the location of ShakeMap install; default is %s.' % shakehome)
    args = parser.parse_args()
    if args.dirind == -1:
        args.directivity = False
    else:
        args.directivity = True
    main(args)
